INCLUDES += -I$(RIOTBASE)/cpu/mc1322x/include -I$(RIOTBASE)/cpu/mc1322x/maca/include -I$(RIOTBASE)/boards/redbee-econotag/drivers/include -I$(RIOTBASE)/sys/include

MODULE =mc1322x

include $(MAKEBASE)/Makefile.base
