export PROJECT = test_hwtimer
include ../Makefile.tests_common

ifeq ($(BOARD),iot-lab_M3)
        include Makefile.iot-lab_M3
        #USEMODULE += at86rf231
endif

include $(RIOTBASE)/Makefile.include
